/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: jc1245 (https://sketchfab.com/jasperchui2007)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-macbook-pro-16-inch-2021-6a42b31bac064b00a91fbfebec07c852
title: Apple MacBook Pro 16 inch 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mac.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.45, 0.09, -0.57]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.011']} />
          </group>
          <group position={[0, 0.1, -1.01]} rotation={[-1.92, 0, 0]}>
            <group position={[-0.03, 0.62, 1.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[32.94, 32.94, 33.49]}>
              <mesh geometry={nodes.Object_23.geometry} material={materials['Material.017']} />
            </group>
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.008']} />
          </group>
          <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.014']} />
          <group position={[-1.49, 0.09, -0.76]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.010']} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
          <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
          <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mac.gltf')
